modLoader="javafml"
loaderVersion="[44,)"
license="All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
modId="jags"
version="${file.jarVersion}"
displayName="JAGS"
logoFile="logo.png"
authors="UnRealDinnerbone"
description='''
Adds a grass seed to Minecraft.
'''
[[dependencies.jags]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="BOTH"
[[dependencies.jags]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
[[dependencies.jags]]
modId="trenzalore"
mandatory=true
versionRange="[${trenzalore_version},)"
ordering="NONE"
side="BOTH"