modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
modId="jags"
version = "${mod_version}"
displayName="Just Another Grass Seed"
logoFile="assets/jags/logo.png"
credits=""
authors="UnRealDinnerbone"
description="Adds a grass seed."
[[dependencies.javd]]
modId = "neoforge"
required = true
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.javd]]
modId = "minecraft"
required = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.javd]]
modId = "trenzalore"
required = true
versionRange = "[${trenzalore_version},)"
ordering = "NONE"
side = "BOTH"